version: 2

sources:
  - name: comercial
    description: Banco réplica do SAP da Adventure Works.
    schema: dbt_ivanpinheiro_marts
    tables:         
      
      - name: dim_clientes
        description: Tabela dimensão dos clientes, juntando as tabelas clientes, pessoas, territórios e países cadastrados na Adventure Works.
        columns:
          - name: sk_cliente
            description: Chave primária da tabela dos clientes das vendas.
            tests:
              - unique
              - not_null
          - name: id_cliente
            description: Chave candidata da tabela dos clientes das vendas.
            tests:
              - unique
              - not_null
      
      - name: dim_razoes_pedidos
        description: Tabela dimensão das razões para cada pedido das vendas na Adventure Works.
        columns:
          - name: sk_razoes_pedidos
            description: Chave primária da tabela das razões dos pedidos.
            tests:
              - unique
              - not_null
          - name: tipo_razao_da_venda
            description: Coluna com o tipo da razão do pedido.
            tests:
              - not_null
              - accepted_values:
                  values: ['Other', 'Promotion', 'Marketing']
      
      - name: dim_enderecos
        description: Tabela dimensão dos endereços cadastrados na Adventure Works.
        columns:
          - name: sk_endereco
            description: Chave primária da tabela dos endereços.
            tests:
              - unique
              - not_null
          - name: id_endereco
            description: Chave candidata da tabela dos endereços.
            tests:
              - unique
              - not_null
      
      - name: dim_produtos
        description: Tabela dimensão dos produtos cadastrados na Adventure Works.
        columns:
          - name: sk_produto
            description: Chave primária da tabela dos produtos.
            tests:
              - unique
              - not_null
          - name: id_produto
            description: Chave candidata da tabela dos produtos.
            tests:
              - unique
              - not_null
      
      - name: fct_vendas
        description: Tabela fato dos pedidos das vendas da Adventure Works.
        columns:
          - name: sk_venda
            description: Chave primária da tabela dos pedidos das vendas.
            tests:
              - unique
              - not_null
          - name: tipo_do_cartao_de_credito
            description: Coluna com o tipo do cartão de crédito usado para realizar o pedido.
            tests:
              - accepted_values:
                  values: ['Vista', 'SuperiorCard', 'Distinguish', 'ColonialVoice']
