version: 2

sources:
  - name: comercial
    description: Banco réplica do SAP da Adventure Works.
    schema: dbt_ivanpinheiro_marts
    tables:         
      - name: dim_clientes
        description: Tabela dimensão dos clientes, juntando as tabelas clientes, pessoas, territórios e países cadastrados na Adventure Works.
        columns:
          - name: sk_cliente
            description: Chave primária da tabela dos clientes das vendas.
            tests:
              - unique
              - not_null
      - name: dim_razoes_pedidos
        description: Tabela dimensão das razões para cada pedido das vendas na Adventure Works.
        columns:
          - name: sk_razoes_pedidos
            description: Chave primária da tabela das razões dos pedidos.
            tests:
              - unique
              - not_null